[settings]
time_base = "Relative"
ticks_per_frame = 8
frame_min = 0
frame_max = 7
frame_start = 0

# Loop animation
[[script]]
run_at_frame = 7
action = "SetFrameNext"
frame_index = 0

# Blink Red
[[script]]
run_every_n_ticks = "8+2"
action = "SetSpriteColor"
color = "#ff0000"
[[script]]
run_every_n_ticks = "8+6"
action = "SetSpriteColor"
color = "#ffffff"

# Transition to regular run animation after 2.5 loops
# (8 ticks per frame * 8 frames * 2.5 = 160)
# [[script]]
# run_at_tick = 160
# action = "ChangeAnimation"
# animation_asset_key = "animation.player.Run"
# transfer_progress = true
