[settings]
time_base = "Relative"
tick_quant = "8"
ticks_per_frame = 8
frame_min = 1
frame_max = 3
frame_start = 1

[[script]]
run_on_slot_enable = "Damaged"
action = "PlayAudio"
volume = 0.7
asset_key = "audio.game.PlayerGetsDamaged"

[[script]]
run_on_slot_enable = "XpOrb"
action = "PlayAudio"
volume = 0.5
asset_key = "audio.game.XpOrbs"

[[script]]
run_on_playback_control = "Start"
action = "PlayAudio"
asset_key = "audio.game.WallSlide"

[[script]]
run_on_playback_control = "Stop"
action = "StopAudio"
asset_key = "audio.game.WallSlide"


# LOOP
[[script]]
run_at_frame = 3
action = "SetFrameNext"
frame_index = 1

# Support left/right flipping
[[script]]
run_on_slot_enable = "DirectionLeft"
action = "SetSpriteFlip"
flip_x = true
[[script]]
run_on_slot_enable = "DirectionRight"
action = "SetSpriteFlip"
flip_x = false