# fn_params_layout = "Vertical"
merge_derives = false
imports_granularity = "Module"
use_field_init_shorthand = true
fn_call_width = 40

# unstable?
unstable_features = true
struct_lit_single_line = false
group_imports = "StdExternalCrate"
normalize_comments = true
reorder_impl_items = true
match_block_trailing_comma = true
force_multiline_blocks = true
