[settings]
time_base = "Relative"
tick_quant = "8"
ticks_per_frame = 8
frame_min = 1
frame_max = 12
frame_start = 1

[[script]]
run_on_slot_enable = "Damaged"
action = "PlayAudio"
volume = 0.7
asset_key = "audio.game.PlayerGetsDamaged"

[[script]]
run_on_slot_enable = "XpOrb"
action = "PlayAudio"
volume = 0.5
asset_key = "audio.game.XpOrbs"