atlas_asset_key = "anim.player.Run.sprite"

[settings]
time_base = "Relative"
tick_quant = "8"
ticks_per_frame = 8
frame_min = 0
frame_max = 7
frame_start = 0

[[script]]
run_at_frame = 7
action = "SetFrameNext"
frame_index = 0
