[settings]
time_base = "Relative"
tick_quant = "8"
ticks_per_frame = 8
frame_min = 1
frame_max = 6
frame_start = 1

# LOOP
[[script]]
run_at_frame = 4
action = "SetFrameNext"
frame_index = 2

# TODO: HIT (when player collides with enemy or ground)
#frame_index has to be set at '5' here