[settings]
time_base = "Relative"
tick_quant = "8"
ticks_per_frame = 8
frame_min = 1
frame_max = 5
frame_start = 2

[[script]]
run_on_slot_enable = "Damaged"
action = "PlayAudio"
volume = 0.7
asset_key = "audio.game.PlayerGetsDamaged"

[[script]]
run_on_slot_enable = "XpOrb"
action = "PlayAudio"
volume = 0.5
asset_key = "audio.game.XpOrbs"

[[script]]
run_at_frame = [1, 2, 3, 4, 5]
require_slots_any = ["SerpentRing", "FrenziedAttack"]
action = "SetTicksPerFrame"
ticks_per_frame = 6

# VARIANT 1 INIT
[[script]]
run_on_playback_control = "Start"
forbid_slots_all = ["AttackTransition"]
action = "SetFrameNow"
frame_index = 1

[[script]]
run_on_playback_control = "Start"
if_previous_script_key = "anim.player.Jump"
action = "PlayAudio"
asset_key = "audio.game.BowShoot"

[[script]]
run_on_playback_control = "Start"
if_previous_script_key = "anim.player.Fall"
action = "PlayAudio"
asset_key = "audio.game.BowShoot"

[[script]]
run_on_playback_control = "Start"
if_previous_script_key = "anim.player.BowBasicAir"
action = "PlayAudio"
asset_key = "audio.game.BowShoot"

[[script]]
run_on_playback_control = "Start"
if_previous_script_key = "anim.player.Dash"
action = "PlayAudio"
asset_key = "audio.game.BowShoot"

# Support left/right flipping
[[script]]
run_on_slot_enable = "DirectionLeft"
action = "SetSpriteFlip"
flip_x = true
[[script]]
run_on_slot_enable = "DirectionRight"
action = "SetSpriteFlip"
flip_x = false
